### ISSUE TITLE
[Feature] Get default branches name

### ISSUE THREAD

**Issue by philjones88** [tj-actions/branch-name#124]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

the `is_default` is nice but we have a mix of repo's where we have the legacy `master` named default branch and newer repos with `main`.

Getting the default branches name would help with our GitHub Action workflows being shared easily.

### Describe the solution you'd like?

A new value of `default_name` that returns a string of the name, i.e. `master` or `main`

### Describe alternatives you've considered?

Hardcoding leads to problems sharing out workflow files.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@philjones88 This should be available in the latest release
