### ISSUE TITLE
[BUG] is_default always returns true

### ISSUE THREAD

**Issue by 1337-server** [tj-actions/branch-name#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Tested the example using

`if: steps.branch-name.outputs.is_default == 'false'`

But this check would cause the step to always be passed over, either on a main branch or another branch.

### To Reproduce

1. ubuntu-latest

using this 
```
            -
                name: Set tag for non-default branch
                if: steps.branch-name.outputs.is_default == 'false'
                run: |
                    echo "Branch name is ${{ env.GITHUB_REF_NAME }}"
                    echo "TAG=${{ env.GITHUB_REF_NAME }}" >> $GITHUB_ENV
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Set an ENV variable if not on the main branch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@1337-server Based on the test [here](https://github.com/tj-actions/branch-names/blob/main/.github/workflows/test.yml#L38) `is_default` should be `false` for `pull_request` triggered actions can you verify what event triggered the action ?

![Screen Shot 2022-06-30 at 5 43 37 AM](https://user-images.githubusercontent.com/17484350/176646449-8e95e688-d75c-42ba-a774-0b7bbd805e78.png)

**Comment by 1337-server** [comment]
Since this won't be fixed, I thought I would include some more details and a fix for anyone else who runs into this.

I use this as a check when building for docker to tag the docker image with the branch name, but wanted it to only run this if it's not on the default branch.

Using
`if: steps.branch-name.outputs.is_default == 'false'`
Meant that for some reason, the if would never run and the docker image would never be tagged with the correct label, leading to the default tag being overwritten.

You can see this here, it's on a non-default branch, but still the if step isn't run because it is always returning true on a push, even when on a non-default branch.
https://github.com/1337-server/arm-dependencies/actions/runs/2587168215

I managed to get the behavior I wanted by using
`if: ${{ steps.branch-name.outputs.ref_branch }} != ${{ steps.branch-name.outputs.default_branch }}`
This will correctly run if not on the default branch, and not when on the main branch.

PS. Thanks for this, it's great!

**Comment by jackton1** [comment]
@1337-server Thanks for replicating the bug it should be fixed in the latest release.
