### ISSUE TITLE
[Feature] determine branch-name when tag is pushed/triggers workflow

### ISSUE THREAD

**Issue by arauchberger** [tj-actions/branch-name#158]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

when the workflow is triggered by a created/pushed tag it's hard to find the branch-name the tag is created on.

### Describe the solution you'd like?

i suggest the following approach via `git log ...` (works at least for me):

```yaml
if [[ $GITHUB_REF == *"/tags/"* ]]; then
  IS_TAG=true
  TAG_NAME=$(basename $GITHUB_REF)
  BRANCH_NAME=$(git log -1 --format='%D' $GITHUB_SHA | sed -e 's/.*origin\/\(.*\)/\1/')
else
  IS_TAG=false
  TAG_NAME=''
  BRANCH_NAME=${{ github.head_ref || github.ref_name }} # whether it's a pull_reguest or not
```

### Anything else?

i'm not good in opening/handling PR's on foreign GitHub-projects, that's why i just write this suggestion to still contribute 'a little bit'.

i like your gh-action!
thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arauchberger** [comment]
hi @jackton1,
i see you fixed this. so the the current_branch is also detected if the wf is triggered by a tag.
one more question:
i experienced that my workaround works only if the tag is set on the latest/head-commit. if you tag an older commit the branch still can not be detected. 
will this be an issue for you too?

**Comment by jackton1** [comment]
@arauchberger ~~It would be helpful if you can include an example application which explains the issue you are seeing.~~. No, I don’t think it should be an issue.
