### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by R3x** [tj-actions/branch-name#216]
Hello, 

I would like to report a security vulnerability, would it be possible to get a contact - where I can report the vulnerability to?

**Comment by jackton1** [comment]
@R3x You can report security vulnerabilities here https://github.com/tj-actions/branch-names/security/advisories/new

**Comment by R3x** [comment]
@jackton1 I am not able to access that link, you probably have to enable it!

**Comment by R3x** [comment]
@jackton1 pinging to make sure you have seen this!

**Comment by jackton1** [comment]
HI @R3x, you can forward all information to support@tj-actions.online

**Comment by R3x** [comment]
@jackton1 I am not able to send emails to that email ID, it keeps bouncing
