### ISSUE TITLE
[BUG] branch outputs are <PR>/merge rather than the branch name

### ISSUE THREAD

**Issue by chrisjohnson** [tj-actions/branch-name#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When running the action from a pull_request_review, none of `current_branch`, `head_ref_branch` and `ref_branch` actually include the branch name from the PR.

Here's what I see in the debug output:
```
##[debug]-e "CURRENT_BRANCH=20/merge" \
##[debug]-e "HEAD_REF_BRANCH=" \
##[debug]-e "REF_BRANCH=20/merge" \
```

### To Reproduce

```yaml
      - name: get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: run thing
        run: |
          docker run \
          --pull=always \
          -e "CURRENT_BRANCH=${{ steps.branch-name.outputs.current_branch }}" \
          -e "HEAD_REF_BRANCH=${{ steps.branch-name.outputs.head_ref_branch }}" \
          -e "REF_BRANCH=${{ steps.branch-name.outputs.ref_branch }}" \
          ...
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04, ubuntu-18.04

### Expected behavior?

I'm not sure if my use case (triggering on pull_request_review) just isn't the desired one but my hope would be to have SOME way of consistently getting the branch name from the PR that the review was submitted for

### Relevant log output

```shell
Included above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisjohnson** [comment]
It looks like github.event.pull_request.head.ref includes the right information on a pull_request_review

**Comment by jackton1** [comment]
@chrisjohnson  Sorry for the delay getting to this, the issue has been resolved in the latest release.

**Comment by chrisjohnson** [comment]
Thanks :)
