### ISSUE TITLE
Use of deprecated set-output triggers warnings during workflow.

### ISSUE THREAD

**Issue by matiasmuller7** [tj-actions/branch-name#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

There are still parts of the code using the deprecated variable declaration set-output, which triggers:

`The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

### To Reproduce

1. Add a step in your workflow using: `uses: tj-actions/branch-names@v7.0.2`
2. Observe the Github Actions log

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

That no warning pops up.

### Anything else?

A similar issue was reported here https://github.com/tj-actions/branch-names/issues/180, but it seems that it has not yet been solved.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@matiasmuller7 This has already been resolved  [here](https://github.com/tj-actions/branch-names/pull/181) if you are using a self hosted runner be sure to upgrade if you need to.
