### ISSUE TITLE
[BUG] `set-output` soon to be deprecated 

### ISSUE THREAD

**Issue by eronnen** [tj-actions/branch-name#267]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does this issue exist in the latest version?

- [x] I'm using the latest release

### Describe the bug?

Github actions issues the following warning:

"The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

I saw existing issues about this that were closed but these warnings still exist. any reason why switching from `set-output`  to `>> $GITHUB_OUTPUT` ?

### To Reproduce

Just using the action

### What OS are you seeing the problem on?

all

### Expected behavior?

to not cause any warnings

### Relevant log output

```shell
"The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @eronnen, I’ll recommend verifying the source of the depreciation warning and also confirming that you are using the latest version of the action.

Related to you question about `set-output` vs `GITHUB_OUTPUT`. 

Here’s an excerpt from the link you posted:

```yml
- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```
This is the recommended approach which is currently used [here](https://github.com/tj-actions/branch-names/blob/main/action.yml#L57-L59) and as such shouldn’t generate any depreciation warnings.

This is also confirmed by the test execution [here](https://github.com/tj-actions/branch-names/actions/runs/6752027343) let my know if you run into any other issues or need further clarification. Cheers
