### ISSUE TITLE
[Feature] Pre-merge branch ref for push and/or pull request

### ISSUE THREAD

**Issue by ghost** [tj-actions/branch-name#93]
### Is your feature request related to a problem? Please describe.

 I generally always use non-squashed commits and rebasing. It wouldn't affect me to use the commit just before the CI merge.

### Describe the solution you'd like?

I want to get the commit before Github "messes" with it by generating a merge commit back into master.

### Describe alternatives you've considered?

I could use the merged commit but that generates an annoying set of errors that irk me during checkout.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
Basically `github.event.pull_request.head.sha` if it's a pull request, `github.event.after` if it's a push that's not `deleted: true`.

**Comment by jackton1** [comment]
@SNDST00M Seems you might need to go into more details, about what you were trying to do preferably with an example of the workflow file and the problem you faced that needs to be resolved. Thanks

**Comment by ghost** [comment]
I want to checkout the pre-merge commit and/or ref.

E.g. for PR `"Adopt Browserstack"` w/ `main` <- `feat-browserstack` @ `91a7571`, I want `feat-browserstack`.

https://github.com/SNDST00M/material-dynmap/blob/91a7571/.github/workflows/ci.yml

I want to checkout that branch during my tests instead of the merge branch.

**Comment by jackton1** [comment]
Sounds like you might need to raise the issue here https://github.com/actions/checkout/issues. Since this repo doesn't handle commits.

You should have access to the branch names regardless See: https://github.com/tj-actions/branch-names#usage.

**Comment by ghost** [comment]
They refused pretty adamantly and called the merge commit a "feature" even though it lacks the commit message 😩

**Comment by jackton1** [comment]
Yeah, I also agree that some of the quirks need to be ironed out. 

I'll suggest convincing them, or writing a step that pulls the information you're looking for.

Thanks
